update readme
Substra/substra pull request #323
Opened 2022-11-22 10:59 UTC by RomainGoussault

Signed-off-by: Romain Goussault <romain.goussault@owkin.com>

## Related issue

`#` followed by the number of the issue

## Summary

## Notes

## Please check if the PR fulfills these requirements

- [ ] If necessary, the [changelog](https://github.com/Substra/substra/blob/main/CHANGELOG.md) has been updated
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] The commit message follows the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification
- For any breaking changes, companion PRs have been opened on the following repositories:
  - [ ] [substra-tests](https://github.com/Substra/substra)
  - [ ] [substrafl](https://github.com/Substra/substrafl)
  - [ ] [substra-documentation](https://github.com/Substra/substra-documentation)

2022-11-22 11:03 UTC, ThibaultFy commented on README.md
> +Substra's main usage is in production environments. It has already been deployed and used by hospitals and biotech companies (see the MELLODDY project for instance). Substra can also be used on a sin
Do you have a link for `MELLODDY` ?

2022-11-22 11:05 UTC, ThibaultFy requested changes

2022-11-22 11:05 UTC, ThibaultFy commented on README.md
> +Discover how Substra powers projects solving critical scientific questions in a privacy-preserving way. Read more here.
Need a link for `here`

2022-11-24 09:44 UTC, RomainGoussault commented on README.md
> +Discover how Substra powers projects solving critical scientific questions in a privacy-preserving way. Read more here.
removed it for now

2022-11-24 09:44 UTC, RomainGoussault commented on README.md
> +Substra's main usage is in production environments. It has already been deployed and used by hospitals and biotech companies (see the MELLODDY project for instance). Substra can also be used on a sin
added

2022-11-25 15:47 UTC, ThibaultFy approved these changes

2022-11-25 15:47 UTC, merged